### ISSUE TITLE
Lots of java.lang.IllegalStateExceptions logged with Gradle 3.4-rc-1

### ISSUE THREAD

**Issue by jochenberger** [ben-manes/gradle-versions-plugin#125]
When running the `dependencyUpdates` task with Gradle 3.4, I get a lot of log output:
```
Failed to resolve ::apiElements
Failed to resolve ::implementation
Failed to resolve ::runtimeElements
Failed to resolve ::runtimeOnly
Failed to resolve ::testImplementation
Failed to resolve ::testRuntimeOnly
```
When running with `-i`, the stacktraces are logged too:
```
Failed to resolve ::apiElements
java.lang.IllegalStateException: Resolving configuration 'apiElementsCopy' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:818)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:419)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:414)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:62)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:213)
        at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:156)
        at org.gradle.internal.metaobject.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
        at com.github.benmanes.gradle.versions.updates.Resolver.resolve(Resolver.groovy:64)
        at com.github.benmanes.gradle.versions.updates.Resolver$resolve.call(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_run_closure2$_closure8.doCall(DependencyUpdates.groovy:60)
[...]
```
Not sure what changed inside Gradle, but I guess there needs to be an additional check as to whether the current configuration is "internal".

**Comment by ben-manes** [comment]
From Gradle's [source code](https://github.com/gradle/gradle/blob/c962e4a653d07b3e2ed0ad295a385441ee2c46c6/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L816), it appears we that should filter the configurations by checking [isCanBeResolved()](https://github.com/gradle/gradle/blob/c962e4a653d07b3e2ed0ad295a385441ee2c46c6/subprojects/core/src/main/java/org/gradle/api/artifacts/Configuration.java#L485) first.

**Comment by ben-manes** [comment]
Or it may be that we want to resolve them, since they appear to be api/impl separations. If a clone and `setCanBeResolved(true)` works, we'd bypass this issue without degrading the report.

**Comment by jochenberger** [comment]
The configurations come from the new `java-library` plugin in Gradle 3.4: https://docs.gradle.org/3.4-rc-1/userguide/userguide_single.html#sec:java_library_configurations_graph
I had a glance at the docs there, but I guess I'm not entirely awake yet. But I guess that trying to resolve the copy is probably a good idea.

**Comment by jochenberger** [comment]
Closing in favor of #131
