### ISSUE TITLE
Support for Gradle 5.0

### ISSUE THREAD

**Issue by lacasseio** [ben-manes/gradle-versions-plugin#263]
As Gradle is moving toward better parallel-by-default, we are locking down unsafe behavior. This result in some code failing, or deadlocking as previously unsafe behavior are made safe. Those change can't be made backward compatible as code safety is part of Gradle itself. We try to reserve those change on major version boundaries. Issue https://github.com/ben-manes/gradle-versions-plugin/issues/255 expose one of that unsafe behavior. With this issue, the Gradle team will provide guidance on how to fix the code to support Gradle 5.0 changes.

Our analysis of the plugin code shows that reaching out between projects in non-Gradle managed thread is the issue. To remove the unsafe behavior of the plugin, we suggest following a common pattern of a reporter task per project and a merger task at the root of the project. Basically, each project would have `DependencyUpdatesTask` generating a JSON report which would then be merged by a root project task into the current JSON report generated by the plugin. The root project can infer each reporter task without reaching inside the projects to create a dependency on them. During the execution of the merger task, it will be safe to get the reporter task instances and find the partial report file location.

The proposed structure removes the need to reach across projects as well as provide some parallelism. Each project will be executed in parallel. Within a project, further parallelism could be achieved using the Worker API, however, it doesn't allow project mutation and creating additional `Configuration`/`Dependency` or modifying them in any way would be unsafe.

Don't hesitate to ask more question. It would be best if the change could be released before the release of Gradle 5.0 which is tentatively at the end of this month.

**Comment by ben-manes** [comment]
Thank you. I don't know if we'll meet the 5.0 deadline, as we've mostly aimed for maintenance and are not very active. I know that my priorities would leave this very low, as my focus on other OSS projects has similarly been halted temporarily. We've tried to maintenance this plugin for the community and cherish contributions, so it may be that assistance from someone is needed here. I have always been eager to see Gradle incorporate this functionality someday, though I understand that's never been a priority.

**Comment by ben-manes** [comment]
Thank you @big-guy. Sorry that I won't be able to get to these immediately.

**Comment by MartyIX** [comment]
Just to illustrate the issue, I'm getting the following deprecation warning in Gradle 5.0 RC1:

```
The configuration :research:implementationCopy was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.0-rc-1/userguide/troubleshooting_dependency_resolution.html#configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
```

**Comment by juergenzimmermann** [comment]
The according stacktrace is e.g.:
```
The configuration :annotationProcessorCopy was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.0-rc-1/userguide/troubleshooting_dependency_resolution.html#configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:521)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:511)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at com.github.benmanes.gradle.versions.updates.Resolver.resolve(Resolver.groovy:80)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdates.resolve(DependencyUpdates.groovy:85)
	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_resolveInParallel_closure7$_closure11$_closure12$_closure13.doCall(DependencyUpdates.groovy:76)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovyx.gpars.pa.CallClosure.call(CallClosure.java:47)
	at groovyx.gpars.pa.ClosureMapper.op(ClosureMapper.java:36)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OOMPap.leafTransfer(AbstractParallelAnyArray.java:2255)
	at groovyx.gpars.extra166y.PAS$FJOMap.atLeaf(PAS.java:258)
	at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:118)
	at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
	at jsr166y.ForkJoinTask.doInvoke(ForkJoinTask.java:348)
	at jsr166y.ForkJoinTask.invoke(ForkJoinTask.java:625)
	at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1489)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray.allObjects(AbstractParallelAnyArray.java:306)
	at groovyx.gpars.extra166y.ParallelArrayWithMapping.all(ParallelArrayWithMapping.java:141)
	at groovyx.gpars.GParsPoolUtil.collectParallel(GParsPoolUtil.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_resolveInParallel_closure7$_closure11$_closure12.doCall(DependencyUpdates.groovy:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:405)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.access$300(GroovyCategorySupport.java:71)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:262)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.use(DefaultGroovyMethods.java:575)
	at org.codehaus.groovy.runtime.dgm$825.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)
	at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
	at groovyx.gpars.GParsPool$withExistingPool.call(Unknown Source)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_resolveInParallel_closure7$_closure11.doCall(DependencyUpdates.groovy:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovyx.gpars.pa.CallClosure.call(CallClosure.java:47)
	at groovyx.gpars.pa.ClosureMapper.op(ClosureMapper.java:36)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OOMPap.leafTransfer(AbstractParallelAnyArray.java:2255)
	at groovyx.gpars.extra166y.PAS$FJOMap.atLeaf(PAS.java:258)
	at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:108)
	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
```

**Comment by MartinX3** [comment]
With gradle 5.0 I get a loop while getting my dependency updates.
It wants to parse the meta from spring 2.2, but there is a dependency for a not existing junit jupiter version.
He does not find it and tries again over and over.

Downgrading to gradle 4.10.3 fixes this problem.

**Comment by ben-manes** [comment]
@MartinX3 Since this plugin lets Gradle do the heavy lifting, via the dynamic version of `+`, you try using that in a minimal project. If it fails during a normal compile, it's definitely a Gradle bug and you should open an issue on their github repository. If you can't reproduce it outside of this plugin, then please provide a minimal example. When we resolve these Gradle 5 issues then we'll make sure to debug your scenario.

**Comment by gliptak** [comment]
Current plugin release ```0.27.0``` doesn't show error with Gradle ```5.6.2```

**Comment by lacasseio** [comment]
The direction you should be looking for is summarized in this sample: https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage.html.

**Comment by lacasseio** [comment]
Unfortunately, you will need to use the `allprojects` hook to apply the plugin everywhere which is a bit frowned upon but in this case, it's the only way to achieve the result of "a single plugin apply which affects all projects". In the theoretical sense, that would be a settings plugin but you can still use a "root project" plugin as well.

**Comment by jaredsburrows** [comment]
Safe to close this now? @lacasseio @ben-manes

**Comment by ben-manes** [comment]
Gradle warns about deprecation due to this, but they have not removed it yet (perhaps due to us). I believe it is still an ask.

**Comment by lacasseio** [comment]
If the plugin still does what is explained in the description of the issue, then it's not safe to close. The plugin will break in future Gradle versions if it's not addressed.

**Comment by ianbrandt** [comment]
The plugin now registers a task per project and merges the results in a root accumulator, which is the topology asked for here. This should have been addressed by PR #994, released in [v0.55.0](https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.55.0). Feel free to reopen if you find otherwise.
