### ISSUE TITLE
Most dependencies cannot be resolved

### ISSUE THREAD

**Issue by shashachu** [ben-manes/gradle-versions-plugin#312]
This is a multi-module Android project (Pinterest) and I'm sure it's something we're doing wrong, but the `--info` flag is not providing a lot of additional information:

```Failed to determine the latest version for the following dependencies (use --info for details):
 - android.arch.work:work-runtime
The exception that is the cause of unresolved state: Could not resolve android.arch.work:work-runtime:+.
 - com.adjust.sdk:adjust-android
The exception that is the cause of unresolved state: Could not resolve com.adjust.sdk:adjust-android:+.
 - com.adyen.checkout:core-card
The exception that is the cause of unresolved state: Could not resolve com.adyen.checkout:core-card:+.
 - com.android.installreferrer:installreferrer
The exception that is the cause of unresolved state: Could not resolve com.android.installreferrer:installreferrer:+.
 - com.android.support:appcompat-v7
The exception that is the cause of unresolved state: Could not resolve com.android.support:appcompat-v7:+.
 - com.android.support:cardview-v7
The exception that is the cause of unresolved state: Could not resolve com.android.support:cardview-v7:+.
 - com.android.support:customtabs
The exception that is the cause of unresolved state: Could not resolve com.android.support:customtabs:+.
 - com.android.support:design
The exception that is the cause of unresolved state: Could not resolve com.android.support:design:+.
```

It's not just android dependencies, just including that snippet.

I thought it might be because we're specifying our versions via variables:
```
implementation "com.squareup.okhttp3:logging-interceptor:${rootProject.ext.okHttpVersion}"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:${rootProject.ext.okHttpVersion}"
    implementation "com.squareup.retrofit2:adapter-rxjava2:${rootProject.ext.retrofitVersion}"
    implementation "com.squareup.retrofit2:converter-gson:${rootProject.ext.retrofitVersion}"
```

but even when I changed them to hardcoded strings, we get the same issue.

Is there anything I can do to get more information? Unfortunately I cannot easily provide our gradle files.

We're using Gradle 5.1.1

**Comment by shashachu** [comment]
Actually scrolling back more, I see these:

```
Failed to resolve :Pinterest:productionDebugCompileClasspath
org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'productionDebugCompileClasspathCopy' not found.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:149)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:323)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:139)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:57)
        at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyConstraintHandler.add(DefaultDependencyConstraintHandler.java:55)
        at com.android.build.gradle.internal.dependency.ConstraintHandler.execute(ConstraintHandler.kt:49)
        at com.android.build.gradle.internal.dependency.ConstraintHandler.execute(ConstraintHandler.kt:31)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$2.execute(DefaultUserCodeApplicationContext.java:77)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
```

for each of our flavors. Assume it's related?

**Comment by ben-manes** [comment]
An example multi-module usage with version replacement is in [Caffeine](https://github.com/ben-manes/caffeine). That part works fine, but isn't an android project.

The task iterates each of your configurations and calls `copy()` on it, modifies the version to `+`, and resolves the dependencies. Then it aggregates the report. I'm not sure why this wouldn't be working for you, as I've done it on single module Android projects.

If you run `--info` it should show details. The first part sounded like it couldn't resolve from a repository. Perhaps there are some resolution strategies, etc. that are conflicting somehow?

**Comment by ben-manes** [comment]
Does the stacktrace resolve back into the plugin? You might think about what plugins or configuration could be interacting in a surprising way. The code for us is fairly straightforward, if that helps.

https://github.com/ben-manes/gradle-versions-plugin/blob/4f0b7ce7b8c76531fcd0808c46a00b0a9b582d65/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L108-L109

**Comment by shashachu** [comment]
User error! We have this snippet in our gradle file:
```
afterEvaluate { project ->
        project.configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.version.contains('+')) {
                    throw new GradleException(
                            "Wildcard dependency forbidden: ${requested.group}:${requested.name}:${requested.version}")
                }
            }
        }
    }
```

🤦‍♀ 

I'm not sure why I didn't see that exception in the logs, but you mentioning the resolutionStrategy pointed me in the right direction.

**Comment by ben-manes** [comment]
haha, okay. You can condition that to run if `dependencyUpdates` is not in the task graph. It's a bit of a hack, but seems to work for most.

```
gradle.taskGraph.whenReady { taskGraph ->
  def requested = details.requested
  if (requested.version.contains('+') && !taskGraph.hasTask(dependencyUpdates)) {
    // throw
  }
}
