### ISSUE TITLE
NullPointerException by local AAR

### ISSUE THREAD

**Issue by westito** [ben-manes/gradle-versions-plugin#36]
Local AAR packages cause NullPointerException:
```
repositories {
    jcenter()

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile(name: 'facebook-api-android-aar', ext :'aar')
    compile(name: 'SlidingMenu-aar-1.3', ext :'aar')
}
```

* Exception is:
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.ExactVersionMatcher.compare(ExactVersionMatcher.java:66)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.ChainVersionMatcher.compare(ChainVersionMatcher.java:52)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionMatcher$compare.call(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionMatcher$compare.call(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_composeVersionMapping_closure13.doCall(DependencyUpdates.groovy:158)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.composeVersionMapping(DependencyUpdates.groovy:153)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.this$2$composeVersionMapping(DependencyUpdates.groovy)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$this$2$composeVersionMapping.callCurrent(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.run(DependencyUpdates.groovy:69)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$run.call(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask.dependencyUpdates(DependencyUpdatesTask.groovy:44)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 43 more

**Comment by teslacoil** [comment]
The following works as a quick fix (for me at least). It looked like 'version' was coming out as an empty string rather than null so that's why the `currentVersions[key] == version` doesn't work. It's probably better to make both of them null or empty strings.

Some more debugging info for @jochenberger if it helps, unfortunately I don't have a test case I can share with you as I'm using a flatDir repo that's provided by someone else and haven't tried to create my own.

Resolved latest dependencies: [:flatDirRepo:;default, ...
Dependency DefaultExternalModuleDependency{group='null', name='flatDirRepo', version='null', configuration='default'} does not use a dynamic version
Comparing current with latest dependencies. current: [null:flatDirRepo:null, ...
  latest: [:flatDirRepo:, ...
Checking dependency :flatDirRepo null

    diff --git a/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy b/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
    index 700c139..7b5b695 100644
    --- a/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
    +++ b/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
    @@ -170,7 +170,7 @@ class DependencyUpdates {
         Map<Integer, Map<Map<String, String>, String>> versionInfo = latestVersions.groupBy {
             Map<String, String> key, version ->
           project.logger.info('Checking dependency {}:{}', key.group, key.name)
    -      if (currentVersions[key] == version) {
    +      if (currentVersions[key] == version || currentVersions[key] == null) {
             0
           } else {
             (Math.signum(comparator.compare(version, currentVersions[key]))) as int

**Comment by jochenberger** [comment]
I'd be grateful if someone could provide a test case that leads to the NPE.

**Comment by scompt** [comment]
Here's a pretty simplified test case extracted from an app I'm working on. There are two sections in the `build.gradle` file. The first one, using version 0.5-beta-1 doesn't throw the exception. The second one, using version 0.7 does.

https://www.dropbox.com/s/vr8xrzr739ng3ab/npe_example.tar.gz?dl=0

**Comment by jochenberger** [comment]
Right, somehow the dependency ends up with different keys in the map with the current versions that in the map with latest versions:
```
$ ANDROID_HOME=/tmp gradle -i dU --stacktrace
...
Comparing current with latest dependencies. current: [null:viewpagerindicator-2.4.1:null, com.android.tools.build:gradle:1.0.1], latest: [:viewpagerindicator-2.4.1:, com.android.tools.build:gradle:1.0.1]
Checking dependency :viewpagerindicator-2.4.1
```
Then, the lookup fails. I guess the fix is easy, I'd still prefer a real test case though, as in Spock test case.

**Comment by jochenberger** [comment]
I can think of multiple way to fix this. Either ignore file-based repositories altogether, report modules with `null` versions unresolved or as up-to-date. @ben-manes, any thoughts?

**Comment by jochenberger** [comment]
The problem with the Map lookup is that http://gradle.org/docs/current/javadoc/org/gradle/api/artifacts/ModuleVersionIdentifier.html#getGroup%28%29 seems to work differently as https://gradle.org/docs/current/javadoc/org/gradle/api/artifacts/Dependency.html#getGroup%28%29.

**Comment by ben-manes** [comment]
I prefer listing it as unresolved rather than up-to-date. It highlights that we can't intelligently evaluate that dependency, as `flatDir` may contain jars that really are out of date compared to Maven Central.

I think if we ignored file-based repositories that would cause the dependency to be unresolved in the report. Whether to explicit check or be indirect comes down to a personal preference of what appears cleaner and more obvious in the code. I like the assertion that we need a Spock test case no matter what happens.

**Comment by Rainer-Lang** [comment]
Any news? I have also this problem.

**Comment by ben-manes** [comment]
Can you put together a sample project demonstrating this bug?

**Comment by scompt** [comment]
@ben-manes Here's a link to the example again: https://www.dropbox.com/s/vr8xrzr739ng3ab/npe_example.tar.gz?dl=0

**Comment by ben-manes** [comment]
Thanks, I'll take a look at this next week.

**Comment by ben-manes** [comment]
The `flatDir` repositories are now being ignored since they don't contain metadata. A partial declaration (like in the sample) is listed as unresolved and a full declaration may find updates on a remote repository.

This was the least invasive way to fix this. I'm not familiar with the code since the rewrites to add type safety and json/xml reporters, so this seemed like the best approach.

**Comment by dodgex** [comment]
any eta for an release of this fix?

**Comment by ben-manes** [comment]
I'll take a look at integrating #59 tonight, which may be a better fix than mine. I'll also try to add a unit test to see if I can validate that.

@jochenberger has been handling the releases from his Bintray account, so we'll see if he has some time this week to kick one off.

**Comment by dodgex** [comment]
Thank you for your feedback! :)
