### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'status' on null object

### ISSUE THREAD

**Issue by embee1981** [ben-manes/gradle-versions-plugin#409]
On running dependencyUpdates using version 0.28.0 of the plugin I am getting the following exception. This happens against my companies Nexus server which has various uploads (in a bad state it seems) that only contain

maven-metadata.xml.md5
maven-metadata.xml.sha1

Apologies for the bad formatting, I've attached the full log
[Log.txt](https://github.com/ben-manes/gradle-versions-plugin/files/4928697/Log.txt)

`Caused by: java.lang.NullPointerException: Cannot get property 'status' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
`
Caused by: java.lang.NullPointerException: Cannot get property 'status' on null object

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at com.github.benmanes.gradle.versions.updates.Resolver$_addRevisionFilter_closure7$_closure14$_closure15.doCall(Resolver.groovy:173)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.github.benmanes.gradle.versions.updates.Resolver$_addRevisionFilter_closure7$_closure14$_closure17.doCall(Resolver.groovy:180)`

**Comment by embee1981** [comment]
[Log.txt](https://github.com/ben-manes/gradle-versions-plugin/files/4928702/Log.txt)

**Comment by ben-manes** [comment]
Since it depends on your Nexus server, unfortunately you'll need to do some sleuthing in our code. The NPE is in the following method when trying to call `metadata.status`,

https://github.com/ben-manes/gradle-versions-plugin/blob/7a04f861fac9ba5ca779d4f0279f4d0208ad0467/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L168-L183

Can you try adding a null check and rerun?.
```groovy
boolean accepted = (metadata == null) ||
    ((revision == 'release') && (metadata.status == 'release')) ||
    ((revision == 'milestone') && (metadata.status != 'integration')) ||
    (revision == 'integration') || (selection.candidate.version == 'none')
```

If you bump up the version in `build.gradle` and run `gradle install`, it should be published into your `mavenLocal()` repository. If you include that in your project's build and update the plugin version, it should resolve to the local jar and allow you to test locally. If it looks good, we can merge that fix and release for you.

**Comment by embee1981** [comment]
Thanks for the quick response :-) That fix did the trick, no more exceptions and its able to resolve the dependencies now in our Nexus repo.

**Comment by ben-manes** [comment]
Kicked off the release (via CI). For some reason the sync from jcenter to gradle's plugin repository takes a few hours, but would certainly be live by tomorrow.
