### ISSUE TITLE
StackOverflowError when running via Github Actions

### ISSUE THREAD

**Issue by jordond** [ben-manes/gradle-versions-plugin#488]
Hi, I'm using the latest version of the plugin "0.38.0".

And when I run it locally on my project it works fine. But when I run it via Github Actions about 70% of the time it will fail with a StackOverflowError.

The action is being run on `ubuntu-latest` with JDK 1.8

Here is the log:

```text
2021-03-25T20:00:41.8272712Z Welcome to Gradle 6.8.3!
2021-03-25T20:00:41.8273320Z 
2021-03-25T20:00:41.8274168Z Here are the highlights of this release:
2021-03-25T20:00:41.8276139Z  - Faster Kotlin DSL script compilation
2021-03-25T20:00:41.8277809Z  - Vendor selection for Java toolchains
2021-03-25T20:00:41.8279040Z  - Convenient execution of tasks in composite builds
2021-03-25T20:00:41.8280264Z  - Consistent dependency resolution
2021-03-25T20:00:41.8287911Z 
2021-03-25T20:00:41.8298307Z For more details see https://docs.gradle.org/6.8.3/release-notes.html
2021-03-25T20:00:41.8299454Z 
2021-03-25T20:00:41.9244374Z To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
2021-03-25T20:00:43.5246831Z Daemon will be stopped at the end of the build 
2021-03-25T20:01:48.9264128Z 
2021-03-25T20:01:48.9276417Z > Task :buildSrc:compileKotlin
2021-03-25T20:01:48.9282644Z The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.8.3/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
2021-03-25T20:01:49.0268644Z 
2021-03-25T20:01:49.0277388Z > Task :buildSrc:compileJava NO-SOURCE
2021-03-25T20:01:49.0278586Z > Task :buildSrc:compileGroovy NO-SOURCE
2021-03-25T20:01:49.0279487Z > Task :buildSrc:pluginDescriptors
2021-03-25T20:01:49.0280537Z > Task :buildSrc:processResources NO-SOURCE
2021-03-25T20:01:49.0281600Z > Task :buildSrc:classes UP-TO-DATE
2021-03-25T20:01:49.0282524Z > Task :buildSrc:inspectClassesForKotlinIC
2021-03-25T20:01:49.0283179Z 
2021-03-25T20:01:49.0283741Z > Task :buildSrc:jar
2021-03-25T20:01:49.0285002Z :jar: No valid plugin descriptors were found in META-INF/gradle-plugins
2021-03-25T20:01:49.0285752Z 
2021-03-25T20:01:49.0286367Z > Task :buildSrc:assemble
2021-03-25T20:01:49.0287366Z > Task :buildSrc:compileTestKotlin NO-SOURCE
2021-03-25T20:01:49.1243899Z > Task :buildSrc:pluginUnderTestMetadata
2021-03-25T20:01:49.1245738Z > Task :buildSrc:compileTestJava NO-SOURCE
2021-03-25T20:01:49.1246949Z > Task :buildSrc:compileTestGroovy NO-SOURCE
2021-03-25T20:01:49.1248173Z > Task :buildSrc:processTestResources NO-SOURCE
2021-03-25T20:01:49.1250335Z > Task :buildSrc:testClasses UP-TO-DATE
2021-03-25T20:01:49.1251004Z > Task :buildSrc:test NO-SOURCE
2021-03-25T20:01:49.2241941Z > Task :buildSrc:validatePlugins
2021-03-25T20:01:49.2243085Z > Task :buildSrc:check
2021-03-25T20:01:49.2244584Z > Task :buildSrc:build
2021-03-25T20:02:19.1240265Z 
2021-03-25T20:02:19.1241966Z > Configure project :app
2021-03-25T20:02:19.1245751Z Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
2021-03-25T20:02:20.6243316Z WARNING: API 'BaseVariant.getApplicationIdTextResource' is obsolete and has been replaced with 'VariantProperties.applicationId'.
2021-03-25T20:02:20.6245376Z It will be removed in version 5.0 of the Android Gradle plugin.
2021-03-25T20:02:20.6246223Z For more information, see TBD.
2021-03-25T20:02:20.6248685Z To determine what is calling BaseVariant.getApplicationIdTextResource, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
2021-03-25T20:02:22.9256721Z 
2021-03-25T20:02:22.9258093Z > Configure project :common
2021-03-25T20:02:22.9261450Z Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
2021-03-25T20:02:24.7245921Z 
2021-03-25T20:02:24.7247243Z > Configure project :googlephotos
2021-03-25T20:02:24.7251014Z Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
2021-03-25T20:02:57.5241527Z 
2021-03-25T20:02:57.5242849Z > Task :dependencyUpdates
2021-03-25T20:04:46.5242403Z > Task :dependencyUpdates FAILED
2021-03-25T20:04:46.6290629Z 
2021-03-25T20:04:46.6291488Z FAILURE: Build failed with an exception.
2021-03-25T20:04:46.6291858Z 
2021-03-25T20:04:46.6292219Z * What went wrong:
2021-03-25T20:04:46.6293422Z Execution failed for task ':dependencyUpdates'.
2021-03-25T20:04:46.6294259Z > java.lang.StackOverflowError (no error message)
2021-03-25T20:04:46.6294787Z 
2021-03-25T20:04:46.6295088Z * Try:
2021-03-25T20:04:46.6295932Z Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2021-03-25T20:04:46.6296451Z 
2021-03-25T20:04:46.6296797Z * Exception is:
2021-03-25T20:04:46.6298096Z org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencyUpdates'.
2021-03-25T20:04:46.6300850Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
2021-03-25T20:04:46.6303360Z 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
2021-03-25T20:04:46.6306158Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
2021-03-25T20:04:46.6310319Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
2021-03-25T20:04:46.6315023Z 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
2021-03-25T20:04:46.6318972Z 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
2021-03-25T20:04:46.6332269Z 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
2021-03-25T20:04:46.6336463Z 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
2021-03-25T20:04:46.6340355Z 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
2021-03-25T20:04:46.6343815Z 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
2021-03-25T20:04:46.6347119Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
2021-03-25T20:04:46.6350051Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
2021-03-25T20:04:46.6352928Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
2021-03-25T20:04:46.6356137Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
2021-03-25T20:04:46.6359781Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
2021-03-25T20:04:46.6362986Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2021-03-25T20:04:46.6365816Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2021-03-25T20:04:46.6495674Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2021-03-25T20:04:46.6499118Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2021-03-25T20:04:46.6502279Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
2021-03-25T20:04:46.6505494Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
2021-03-25T20:04:46.6518434Z 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
2021-03-25T20:04:46.6522478Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
2021-03-25T20:04:46.6526559Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
2021-03-25T20:04:46.6529576Z 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
2021-03-25T20:04:46.6534853Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
2021-03-25T20:04:46.6540774Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
2021-03-25T20:04:46.6544270Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
2021-03-25T20:04:46.6766839Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
2021-03-25T20:04:46.6770236Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
2021-03-25T20:04:46.6772423Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
2021-03-25T20:04:46.6774757Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
2021-03-25T20:04:46.6777001Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
2021-03-25T20:04:46.6781563Z 	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:72)
2021-03-25T20:04:46.6785848Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:196)
2021-03-25T20:04:46.6790613Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:189)
2021-03-25T20:04:46.6793817Z 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:39)
2021-03-25T20:04:46.6797017Z 	at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:40)
2021-03-25T20:04:46.6799423Z 	at org.gradle.execution.DefaultBuildWorkExecutor.access$000(DefaultBuildWorkExecutor.java:24)
2021-03-25T20:04:46.6801624Z 	at org.gradle.execution.DefaultBuildWorkExecutor$1.proceed(DefaultBuildWorkExecutor.java:48)
2021-03-25T20:04:46.6804249Z 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
2021-03-25T20:04:46.6807085Z 	at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:40)
2021-03-25T20:04:46.7009280Z 	at org.gradle.execution.DefaultBuildWorkExecutor.execute(DefaultBuildWorkExecutor.java:33)
2021-03-25T20:04:46.7012531Z 	at org.gradle.execution.IncludedBuildLifecycleBuildWorkExecutor.execute(IncludedBuildLifecycleBuildWorkExecutor.java:36)
2021-03-25T20:04:46.7016218Z 	at org.gradle.execution.DeprecateUndefinedBuildWorkExecutor.execute(DeprecateUndefinedBuildWorkExecutor.java:44)
2021-03-25T20:04:46.7019911Z 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.run(BuildOperationFiringBuildWorkerExecutor.java:57)
2021-03-25T20:04:46.7023170Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
2021-03-25T20:04:46.7089913Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
2021-03-25T20:04:46.7094196Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2021-03-25T20:04:46.7097654Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2021-03-25T20:04:46.7100752Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2021-03-25T20:04:46.7104075Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2021-03-25T20:04:46.7107538Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
2021-03-25T20:04:46.7110807Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
2021-03-25T20:04:46.7115202Z 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
2021-03-25T20:04:46.7119404Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
2021-03-25T20:04:46.7123047Z 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:42)
2021-03-25T20:04:46.7127889Z 	at org.gradle.initialization.DefaultGradleLauncher.runWork(DefaultGradleLauncher.java:260)
2021-03-25T20:04:46.7227572Z 	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:172)
2021-03-25T20:04:46.7230631Z 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
2021-03-25T20:04:46.7233641Z 	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
2021-03-25T20:04:46.7236717Z 	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
2021-03-25T20:04:46.7307254Z 	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
2021-03-25T20:04:46.7309950Z 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
2021-03-25T20:04:46.7312722Z 	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
2021-03-25T20:04:46.7316028Z 	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
2021-03-25T20:04:46.7318797Z 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
2021-03-25T20:04:46.7321655Z 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
2021-03-25T20:04:46.7325247Z 	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
2021-03-25T20:04:46.7328985Z 	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
2021-03-25T20:04:46.7332936Z 	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:77)
2021-03-25T20:04:46.7409831Z 	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
2021-03-25T20:04:46.7413873Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
2021-03-25T20:04:46.7417287Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
2021-03-25T20:04:46.7420808Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
2021-03-25T20:04:46.7424500Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
2021-03-25T20:04:46.7427725Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2021-03-25T20:04:46.7430684Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2021-03-25T20:04:46.7433799Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2021-03-25T20:04:46.7437369Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2021-03-25T20:04:46.7440672Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
2021-03-25T20:04:46.7443921Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
2021-03-25T20:04:46.7448607Z 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
2021-03-25T20:04:46.7452727Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
2021-03-25T20:04:46.7456158Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
2021-03-25T20:04:46.7459504Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:54)
2021-03-25T20:04:46.7462222Z 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
2021-03-25T20:04:46.7465843Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:53)
2021-03-25T20:04:46.7468883Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
2021-03-25T20:04:46.7472733Z 	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
2021-03-25T20:04:46.7476030Z 	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:49)
2021-03-25T20:04:46.7479250Z 	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:32)
2021-03-25T20:04:46.7483870Z 	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:27)
2021-03-25T20:04:46.7494382Z 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
2021-03-25T20:04:46.7498413Z 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
2021-03-25T20:04:46.7502407Z 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
2021-03-25T20:04:46.7506723Z 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
2021-03-25T20:04:46.7549952Z 	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
2021-03-25T20:04:46.7553575Z 	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
2021-03-25T20:04:46.7648511Z 	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
2021-03-25T20:04:46.7698316Z 	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
2021-03-25T20:04:46.7702997Z 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
2021-03-25T20:04:46.7707125Z 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
2021-03-25T20:04:46.7711530Z 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
2021-03-25T20:04:46.7716470Z 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
2021-03-25T20:04:46.7722504Z 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
2021-03-25T20:04:46.7727308Z 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
2021-03-25T20:04:46.7731673Z 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
2021-03-25T20:04:46.7735219Z 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
2021-03-25T20:04:46.7738614Z 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
2021-03-25T20:04:46.7741127Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2021-03-25T20:04:46.7744101Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7747648Z 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
2021-03-25T20:04:46.7750785Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7754092Z 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
2021-03-25T20:04:46.7757286Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7760954Z 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
2021-03-25T20:04:46.7764615Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7767456Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
2021-03-25T20:04:46.7770105Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
2021-03-25T20:04:46.7771871Z 	at org.gradle.util.Swapper.swap(Swapper.java:38)
2021-03-25T20:04:46.7773838Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
2021-03-25T20:04:46.7776862Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7779883Z 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
2021-03-25T20:04:46.7782891Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7785764Z 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
2021-03-25T20:04:46.7789115Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2021-03-25T20:04:46.7792084Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7795484Z 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
2021-03-25T20:04:46.7868034Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2021-03-25T20:04:46.7871147Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-03-25T20:04:46.7928775Z 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
2021-03-25T20:04:46.7931816Z 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
2021-03-25T20:04:46.7934381Z 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2021-03-25T20:04:46.7936622Z 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2021-03-25T20:04:46.7938925Z 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2021-03-25T20:04:46.7941033Z Caused by: java.lang.StackOverflowError
2021-03-25T20:04:46.7942599Z 	at org.gradle.internal.SystemProperties.getLineSeparator(SystemProperties.java:79)
2021-03-25T20:04:46.7945702Z 	at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput.<init>(AbstractLineChoppingStyledTextOutput.java:32)
2021-03-25T20:04:46.7949533Z 	at org.gradle.internal.logging.text.LinePrefixingStyledTextOutput.<init>(LinePrefixingStyledTextOutput.java:32)
2021-03-25T20:04:46.7952340Z 	at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:237)
2021-03-25T20:04:46.7954925Z 	at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:259)
2021-03-25T20:04:46.7958047Z 	at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:259)
2021-03-25T20:04:46.7960336Z 	at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:259)
 [this is repeated a bunch of times]
2021-03-25T20:04:47.2969660Z 
2021-03-25T20:04:47.2969892Z 
2021-03-25T20:04:47.2970439Z * Get more help at https://help.gradle.org
2021-03-25T20:04:47.2970895Z 
2021-03-25T20:04:47.2971262Z BUILD FAILED in 4m 11s
2021-03-25T20:04:47.2971763Z 1 actionable task: 1 executed
```

**Comment by ben-manes** [comment]
hmm, I don't have any ideas here. I suppose you could run via the action's docker container to reproduce. It seems to be internal to Gradle and not our direct usage.

There is a github action that uses this plugin, so I imagine it should work.
https://github.com/marketplace/actions/gradle-update-checker

**Comment by jordond** [comment]
Yeah it's weird. It was working perfectly fine for the last 3 months or so.

I'll have to play around with it some more. Thanks.

**Comment by jaredsburrows** [comment]
The https://github.com/marketplace/actions/gradle-update-checker is using `0.25.0`(https://github.com/MeilCli/gradle-update-check-action/blob/master/src/main.ts#L13). It might be worth sending them a PR to update it.
