### ISSUE TITLE
Resource missing error when trying to fetch maven information

### ISSUE THREAD

**Issue by igorkurek** [ben-manes/gradle-versions-plugin#555]
I've been using the plugin for a long time, but it seems that it stopped working for my projects. When I try to run `./gradlew dependencyUpdates --info` I get 404 errors on maven XML files. I'm using Gradle 7.1.1 with Android project and latset version of plugin, `classpath "com.github.ben-manes:gradle-versions-plugin:0.39.0"` 

```
> Task :app:dependencyUpdates
Caching disabled for task ':app:dependencyUpdates' because:
  Build cache is disabled
Task ':app:dependencyUpdates' is not up-to-date because:
  Task.upToDateWhen is false.
Resolving :app project buildscript with repositories:
Resolving :app project configurations with repositories:
 - Google: https://dl.google.com/dl/android/maven2/
 - MavenRepo: https://repo.maven.apache.org/maven2/
 - maven: https://plugins.gradle.org/m2/
 - maven2: https://jitpack.io
 - maven3: https://maven.fabric.io/public
 - Google2: https://dl.google.com/dl/android/maven2/
 - MavenRepo2: https://repo.maven.apache.org/maven2/
 - maven4: https://plugins.gradle.org/m2/
 - maven5: https://jitpack.io
 - maven6: https://maven.fabric.io/public
 - Google3: https://dl.google.com/dl/android/maven2/
 - MavenRepo3: https://repo.maven.apache.org/maven2/
 - maven7: https://plugins.gradle.org/m2/
 - maven8: https://jitpack.io
 - maven9: https://maven.fabric.io/public
Registered task dependencies: app:_agp_internal_javaPreCompileDebugAndroidTest_kaptClasspathCopy
Starting dependency analysis
Registered task dependencies: app:_agp_internal_javaPreCompileDebugUnitTest_kaptClasspathCopy
Starting dependency analysis
Registered task dependencies: app:_agp_internal_javaPreCompileDebug_kaptClasspathCopy
Starting dependency analysis
Registered task dependencies: app:_agp_internal_javaPreCompileReleaseUnitTest_kaptClasspathCopy
Starting dependency analysis
Registered task dependencies: app:_agp_internal_javaPreCompileRelease_kaptClasspathCopy
Starting dependency analysis
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://jitpack.io/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://maven.fabric.io/public/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://jitpack.io/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://maven.fabric.io/public/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://jitpack.io/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Resource missing. [HTTP GET: https://maven.fabric.io/public/org/jacoco/org.jacoco.ant/maven-metadata.xml]
Registered task dependencies: app:androidTestCompileOnlyCopy
Starting dependency analysis
Registered task dependencies: app:androidTestCompileOnlyDependenciesMetadataCopy
Starting dependency analysis
Registered task dependencies: app:androidTestDebugCompileOnlyCopy
Starting dependency analysis
Registered task dependencies: app:androidTestDebugCompileOnlyDependenciesMetadataCopy
Starting dependency analysis
Registered task dependencies: app:androidTestReleaseCompileOnlyCopy
Starting dependency analysis
Registered task dependencies: app:androidTestReleaseCompileOnlyDependenciesMetadataCopy
Starting dependency analysis
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://jcenter.bintray.com/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://jitpack.io/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://maven.fabric.io/public/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://jcenter.bintray.com/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://jitpack.io/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://maven.fabric.io/public/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://jcenter.bintray.com/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://jitpack.io/androidx/databinding/databinding-compiler/maven-metadata.xml]
Resource missing. [HTTP GET: https://maven.fabric.io/public/androidx/databinding/databinding-compiler/maven-metadata.xml]
```

**Comment by ben-manes** [comment]
Gradle will query your repositories searching for the dependency metadata. It should check each one in case multiple repositories contains a dependency, but one has a later version. For example the `jacoco` dependency is on Maven Central and not on Google's, so this makes sense. You can use content filters to exclude repositories from being checked, which will help speed up the resolution.

Is there a report failure or just these log messages causing concern?

**Comment by ben-manes** [comment]
Also note that Gradle does not remove repository duplicates, so your 3x repeats will probably slow down resolution.

**Comment by igorkurek** [comment]
Okay, thanks for explanation. I thought that the issue is related to those Maven metadatafiles, but I've run it again in verbose mode and I can see that it's caused by something different:

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method isNonStable() for arguments [1.5.1] on task ':app:dependencyUpdates' of type com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask.
        at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)
        ...
Cause 4: org.gradle.api.InvalidUserCodeException: There was an error while evaluating a component selection rule for org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.1.
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentSelectionRulesProcessor.processRule(ComponentSelectionRulesProcessor.java:81)
        ...
```

So I think there's something wrong with my configuration for rejecting unstable versions:

```groovy
tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
    }
}
```

**Comment by igorkurek** [comment]
Okay, I've fixed the definition of `isNonStable` on readme, because of `it` parameter being shadowed, I've rrnamed it to `qualifier` and now everything works fine:
```groovy
def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { qualifier -> version.toUpperCase().contains(qualifier) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}
```

Thank You for Your help
