### ISSUE TITLE
Exception in IntelliJ 2024.1

### ISSUE THREAD

**Issue by oneiros-de** [ben-manes/gradle-versions-plugin#860]
IntelliJ 2024.1 throws an error and suggests to disable the plugin:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.tarn2206.actions.RefreshAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: tarn.gradle.dependencies]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by ben-manes** [comment]
tarn.gradle.dependencies is something else. That’s seems to be 
https://github.com/tarn2206/gradle-dependencies-checker
